### ISSUE TITLE
what is the purpose of using constructor? 

### ISSUE THREAD

**Issue by hshahwan** [GSG-K3/to-do-BRNH#25]
https://github.com/GSG-K3/to-do-BRNH/blob/f4c65f992234fc3b5f851400b714a9f5d8b8b229/logic.js#L22

**Comment by Rahaf-96** [comment]
To check if the input is Array or not.

**Comment by Rahaf-96** [comment]
We tried to use typeOf(todos) and the result was Object not Array

**Comment by hshahwan** [comment]
I see, also you can check it the result is an array or not by using ``` The Array.isArray() ```
